pipeline {
	agent any
		stages {
			stage('Clean stage') {
				steps {
					dir("MiscTopicsDemo") {
						withMaven(maven: 'maven_3_6_3') {
							bat 'mvn clean'
						}
					}
				}
			}
			stage('Compile stage') {
				steps {
					dir("MiscTopicsDemo") {
						withMaven(maven: 'maven_3_6_3') {
							bat 'mvn compile'
						}
					}
				}
			}
			stage('Install stage') {
				steps {
					dir("MiscTopicsDemo") {
						withMaven(maven: 'maven_3_6_3') {
							bat 'mvn install'
						}
					}
				}
			}
		}
}
